// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'flowchart-content': string;
  'flowchart-img': string;
  'flowchart-wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
