// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'main-content': string;
  'main-img': string;
  'main-wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
